# Site
title:          "Wei-Cheng's blog"
bio:            'Just a blog'
description:    "Basically, I'm not interested in doing research and I never have been. I'm interested in understanding, which is quite a different thing. And often to understand something you have to work it out yourself because no one else has done it."
picture:        'assets/img/about.jpg'
locale:         en_US
url:            https://supernovatitanium.github.io/Blog


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
email: supernovatitanium@gmail.com
twitter: username
facebook: 
#google:
  #plus: #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
github: SupernovaTitanium
stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: Supernovatitanium
#xing: username
instagram: username
lastfm: username
tumblr: username
#pinterest: username
#foursquare: username
steam: username
#dribbble: username
youtube: username
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"


# Comments
disqus_shortname: alperenbozkurt-net


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
